# Generated by Django 5.2.8 on 2025-12-02 16:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("type", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("PENDING", "PENDING"),
                            ("RECEIVED", "RECEIVED"),
                            ("STARTED", "STARTED"),
                            ("SUCCESS", "SUCCESS"),
                            ("FAILURE", "FAILURE"),
                            ("REVOKED", "REVOKED"),
                            ("REJECTED", "REJECTED"),
                            ("RETRY", "RETRY"),
                            ("IGNORED", "IGNORED"),
                        ],
                        max_length=20,
                    ),
                ),
                ("sent_at", models.DateTimeField()),
                ("received_at", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("succeeded_at", models.DateTimeField(blank=True, null=True)),
                ("failed_at", models.DateTimeField(blank=True, null=True)),
                ("retried_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("rejected_at", models.DateTimeField(blank=True, null=True)),
                (
                    "last_updated",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("runtime", models.FloatField(blank=True, null=True)),
                ("args", models.TextField(blank=True, null=True)),
                ("kwargs", models.TextField(blank=True, null=True)),
                ("eta", models.DateTimeField(blank=True, null=True)),
                ("expires", models.DateTimeField(blank=True, null=True)),
                ("retries", models.IntegerField(blank=True, null=True)),
                ("exchange", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "routing_key",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("root_id", models.CharField(blank=True, max_length=255, null=True)),
                ("parent_id", models.CharField(blank=True, max_length=255, null=True)),
                ("worker", models.CharField(blank=True, max_length=255, null=True)),
                ("result", models.TextField(blank=True, null=True)),
                ("exception", models.TextField(blank=True, null=True)),
                ("traceback", models.TextField(blank=True, null=True)),
                ("children", models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.CreateModel(
            name="TaskResult",
            fields=[
                (
                    "id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("type", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("PENDING", "PENDING"),
                            ("RECEIVED", "RECEIVED"),
                            ("STARTED", "STARTED"),
                            ("SUCCESS", "SUCCESS"),
                            ("FAILURE", "FAILURE"),
                            ("REVOKED", "REVOKED"),
                            ("REJECTED", "REJECTED"),
                            ("RETRY", "RETRY"),
                            ("IGNORED", "IGNORED"),
                        ],
                        max_length=20,
                    ),
                ),
                ("queue", models.CharField(blank=True, max_length=255, null=True)),
                ("result", models.TextField(blank=True, null=True)),
                ("traceback", models.TextField(blank=True, null=True)),
                ("ignored", models.BooleanField(default=False)),
                ("args", models.JSONField(blank=True, default=list)),
                ("kwargs", models.JSONField(blank=True, default=dict)),
                ("retries", models.IntegerField(default=0)),
                ("worker", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
