# Generated by Django 5.2.8 on 2025-12-02 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("insight", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
