# Generated by Django 5.2.8 on 2025-12-02 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("insight", "0002_alter_task_sent_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActiveTaskRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task_id", models.CharField(max_length=255, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("args", models.JSONField(default=list)),
                ("kwargs", models.JSONField(default=dict)),
                ("worker_hostname", models.CharField(max_length=255)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("last_seen", models.DateTimeField(auto_now=True)),
                ("status", models.CharField(default="active", max_length=50)),
            ],
            options={
                "ordering": ["-last_seen"],
            },
        ),
        migrations.CreateModel(
            name="QueueStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("messages_ready", models.IntegerField(default=0)),
                ("messages_unacknowledged", models.IntegerField(default=0)),
                ("total_messages", models.IntegerField(default=0)),
                ("consumers", models.IntegerField(default=0)),
                ("state", models.CharField(default="running", max_length=50)),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="WorkerStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hostname", models.CharField(max_length=255, unique=True)),
                ("pid", models.IntegerField(blank=True, null=True)),
                ("state", models.CharField(default="unknown", max_length=50)),
                ("is_active", models.BooleanField(default=False)),
                ("active_concurrency", models.IntegerField(default=0)),
                ("total_processed", models.BigIntegerField(default=0)),
                ("total_cancelled", models.BigIntegerField(default=0)),
                ("total_failed", models.BigIntegerField(default=0)),
                ("load_avg", models.FloatField(default=0.0)),
                ("prefetch_count", models.IntegerField(default=0)),
                ("uptime_seconds", models.IntegerField(default=0)),
                ("pool_type", models.CharField(default="", max_length=50)),
                (
                    "max_tasks_per_child",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("max_memory_per_child", models.IntegerField(blank=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("last_ping", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["hostname"],
            },
        ),
    ]
