# Generated by Django 5.2.8 on 2025-12-02 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("insight", "0003_activetaskrecord_queuestatus_workerstatus"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="state",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("RECEIVED", "Received"),
                    ("started", "Started"),
                    ("success", "Success"),
                    ("failure", "Failure"),
                    ("REVOKED", "REVOKED"),
                    ("REJECTED", "REJECTED"),
                    ("RETRY", "RETRY"),
                    ("IGNORED", "IGNORED"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="taskresult",
            name="state",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("RECEIVED", "Received"),
                    ("started", "Started"),
                    ("success", "Success"),
                    ("failure", "Failure"),
                    ("REVOKED", "REVOKED"),
                    ("REJECTED", "REJECTED"),
                    ("RETRY", "RETRY"),
                    ("IGNORED", "IGNORED"),
                ],
                max_length=20,
            ),
        ),
    ]
