# Generated by Django 5.2.8 on 2025-12-03 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("insight", "0005_delete_taskresult"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("status", models.CharField(max_length=50)),
                ("worker", models.CharField(blank=True, max_length=100, null=True)),
                ("result", models.JSONField(blank=True, null=True)),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="insight.task",
                    ),
                ),
            ],
            options={
                "verbose_name": "Task Event",
                "verbose_name_plural": "Task Events",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["worker"], name="insight_tas_worker_72b298_idx"
                    ),
                    models.Index(
                        fields=["status"], name="insight_tas_status_c58fac_idx"
                    ),
                    models.Index(
                        fields=["task", "status"], name="insight_tas_task_id_a16940_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status", "SUCCESS")),
                        fields=("task", "status"),
                        name="unique_success_per_task",
                    )
                ],
            },
        ),
    ]
