# Generated by Django 5.2.8 on 2025-12-03 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("insight", "0010_rename_state_task_status_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="exchange",
        ),
        migrations.RemoveField(
            model_name="task",
            name="routing_key",
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(fields=["name"], name="insight_tas_name_3ba8dd_idx"),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(fields=["status"], name="insight_tas_status_f8cdb6_idx"),
        ),
    ]
