# Generated by Django 5.2.8 on 2025-12-03 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("insight", "0011_remove_task_exchange_remove_task_routing_key_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="runtime",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
