# Generated by Django 5.2.8 on 2025-12-03 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("insight", "0013_task_provider"),
    ]

    operations = [
        migrations.CreateModel(
            name="SftpGo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event",
                    models.CharField(
                        db_index=True,
                        help_text="upload, download, delete, rename, etc.",
                        max_length=50,
                    ),
                ),
                ("username", models.CharField(db_index=True, max_length=255)),
                ("ip", models.GenericIPAddressField(db_index=True)),
                ("role", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "uid",
                    models.CharField(
                        blank=True,
                        help_text="SFTPGo internal user ID",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("protocol", models.CharField(max_length=20)),
                (
                    "path",
                    models.TextField(help_text="Full filesystem path on the server"),
                ),
                (
                    "virtual_path",
                    models.TextField(help_text="Path as seen by the user"),
                ),
                (
                    "file_size",
                    models.BigIntegerField(default=0, help_text="Size in bytes"),
                ),
                (
                    "object_name",
                    models.TextField(
                        blank=True, help_text="Usually the filename", null=True
                    ),
                ),
                ("object_type", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "status",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "Success"), (2, "Error")], db_index=True
                    ),
                ),
                (
                    "timestamp",
                    models.BigIntegerField(
                        help_text="SFTPGo nanosecond timestamp (Unix epoch * 1e9 + ns)"
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(
                        db_index=True,
                        help_text="Human-readable ISO datetime from SFTPGo",
                    ),
                ),
                (
                    "elapsed",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Operation time in milliseconds",
                        null=True,
                    ),
                ),
                (
                    "object_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Extra object data (user/folder JSON when applicable)",
                    ),
                ),
                ("error", models.TextField(blank=True, null=True)),
                ("received_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "verbose_name": "SFTPGo Event",
                "verbose_name_plural": "SFTPGo Events",
                "ordering": ["-date"],
                "indexes": [
                    models.Index(
                        fields=["username", "event"],
                        name="insight_sft_usernam_1b7c3c_idx",
                    ),
                    models.Index(fields=["date"], name="insight_sft_date_2b568a_idx"),
                    models.Index(
                        fields=["protocol"], name="insight_sft_protoco_b40978_idx"
                    ),
                ],
            },
        ),
    ]
