# Generated by Django 5.2.8 on 2025-12-03 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("insight", "0014_sftpgo"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="WorkerStatus",
            new_name="Workers",
        ),
    ]
