# Generated by Django 5.2.8 on 2025-12-03 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("insight", "0015_rename_workerstatus_workers"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="QueueStatus",
            new_name="Queue",
        ),
    ]
