# Generated by Django 5.2.8 on 2025-12-02 15:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ActiveTaskRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task_id", models.CharField(max_length=255, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("args", models.JSONField(default=list)),
                ("kwargs", models.JSONField(default=dict)),
                ("worker_hostname", models.CharField(max_length=255)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("last_seen", models.DateTimeField(auto_now=True)),
                ("status", models.CharField(default="active", max_length=50)),
            ],
            options={
                "db_table": "celery_active_tasks",
            },
        ),
        migrations.CreateModel(
            name="Package",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "original",
                    models.FileField(blank=True, null=True, upload_to="packages/"),
                ),
                (
                    "manifest",
                    models.FileField(blank=True, null=True, upload_to="manifests/"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="QueueStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("messages_ready", models.IntegerField(default=0)),
                ("messages_unacknowledged", models.IntegerField(default=0)),
                ("total_messages", models.IntegerField(default=0)),
                ("consumers", models.IntegerField(default=0)),
                ("state", models.CharField(default="running", max_length=50)),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "celery_queue_status",
            },
        ),
        migrations.CreateModel(
            name="WorkerStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hostname", models.CharField(max_length=255, unique=True)),
                ("pid", models.IntegerField(blank=True, null=True)),
                ("state", models.CharField(default="unknown", max_length=50)),
                ("is_active", models.BooleanField(default=False)),
                ("active_concurrency", models.IntegerField(default=0)),
                ("total_processed", models.BigIntegerField(default=0)),
                ("total_cancelled", models.BigIntegerField(default=0)),
                ("total_failed", models.BigIntegerField(default=0)),
                ("load_avg", models.FloatField(default=0.0)),
                ("prefetch_count", models.IntegerField(default=0)),
                ("uptime_seconds", models.IntegerField(default=0)),
                ("pool_type", models.CharField(default="", max_length=50)),
                (
                    "max_tasks_per_child",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("max_memory_per_child", models.IntegerField(blank=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("last_ping", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "celery_worker_status",
            },
        ),
        migrations.CreateModel(
            name="Provider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("slug", models.SlugField(blank=True, max_length=255)),
                ("active", models.BooleanField(default=False)),
                ("vidra_task", models.CharField(blank=True, max_length=255, null=True)),
                ("queue", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "ordering": ["name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("name", "vidra_task", "queue"),
                        name="unique_provider_task",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Edge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content_id",
                    models.CharField(max_length=255, null=True, unique=True),
                ),
                ("title", models.CharField(max_length=255, null=True)),
                ("creation_time", models.DateTimeField(null=True)),
                ("modification_time", models.DateTimeField(null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("error", "ERROR"), ("done", "SUCCESS")],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("playable", models.BooleanField(default=False)),
                ("content_duration_ms", models.IntegerField(null=True)),
                (
                    "expiry_date",
                    models.DateTimeField(help_text="expired offer", null=True),
                ),
                ("offer_id", models.CharField(max_length=255, null=True)),
                (
                    "provider",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vod.provider",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TaskState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "task_name",
                    models.CharField(
                        help_text="Celery task name (e.g., update_offer_states)",
                        max_length=255,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("started", "Started"),
                            ("success", "Success"),
                            ("failure", "Failure"),
                        ],
                        default="pending",
                        help_text="Current state of the task execution",
                        max_length=10,
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, help_text="When the task started", null=True
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, help_text="When the task finished", null=True
                    ),
                ),
                (
                    "result",
                    models.JSONField(
                        blank=True,
                        help_text='Task result (e.g., {"updated": 5})',
                        null=True,
                    ),
                ),
                (
                    "error",
                    models.TextField(
                        blank=True, help_text="Error message if failed", null=True
                    ),
                ),
                (
                    "duration",
                    models.DurationField(
                        blank=True, help_text="Execution time", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Task States",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["task_name", "state"],
                        name="vod_tasksta_task_na_149c00_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="vod_tasksta_created_c5c3ce_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(blank=True, max_length=255)),
                (
                    "original_package",
                    models.FileField(blank=True, upload_to="packages/"),
                ),
                (
                    "mezzanine_video",
                    models.FileField(blank=True, upload_to="mezzanine/"),
                ),
                (
                    "hevc_archive",
                    models.FileField(blank=True, upload_to="archive/hevc/"),
                ),
                ("dash_directory", models.CharField(blank=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("uploaded", "Uploaded"),
                            ("adi_validated", "ADI Validated"),
                            ("processing", "Processing"),
                            ("ready", "Ready"),
                            ("rejected", "Rejected"),
                            ("error", "Error"),
                        ],
                        default="uploaded",
                        max_length=20,
                    ),
                ),
                ("processing_log", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Stream",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stream_protocol",
                    models.CharField(
                        choices=[("hls", "hls"), ("dash", "dash"), ("mss", "mss")],
                        max_length=4,
                    ),
                ),
                ("uri", models.URLField(max_length=512)),
                (
                    "edge",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="streams",
                        to="vod.edge",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("edge", "stream_protocol"), name="unq_edge_proto"
                    )
                ],
            },
        ),
    ]
