# Generated by Django 5.2.8 on 2025-12-01 17:37

import django.db.models.deletion
import django_extensions.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Package",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "original",
                    models.FileField(blank=True, null=True, upload_to="packages/"),
                ),
                (
                    "manifest",
                    models.FileField(blank=True, null=True, upload_to="manifests/"),
                ),
            ],
            options={
                "get_latest_by": "modified",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Worker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(editable=False, max_length=255)),
                ("status", models.CharField(editable=False, max_length=20)),
                ("last_heartbeat", models.DateTimeField(editable=False, null=True)),
                ("is_alive", models.BooleanField(default=False, editable=False)),
                ("active_tasks", models.JSONField(default=list, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name="Provider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("slug", models.SlugField(blank=True, max_length=255)),
                ("active", models.BooleanField(default=False)),
                ("vidra_task", models.CharField(blank=True, max_length=255, null=True)),
                ("queue", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "ordering": ["name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("name", "vidra_task", "queue"),
                        name="unique_provider_task",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Edge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content_id",
                    models.CharField(max_length=255, null=True, unique=True),
                ),
                ("title", models.CharField(max_length=255, null=True)),
                ("creation_time", models.DateTimeField(null=True)),
                ("modification_time", models.DateTimeField(null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("error", "ERROR"), ("done", "SUCCESS")],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("playable", models.BooleanField(default=False)),
                ("content_duration_ms", models.IntegerField(null=True)),
                (
                    "expiry_date",
                    models.DateTimeField(help_text="expired offer", null=True),
                ),
                ("offer_id", models.CharField(max_length=255, null=True)),
                (
                    "provider",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vod.provider",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TaskState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "task_name",
                    models.CharField(
                        help_text="Celery task name (e.g., update_offer_states)",
                        max_length=255,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("started", "Started"),
                            ("success", "Success"),
                            ("failure", "Failure"),
                        ],
                        default="pending",
                        help_text="Current state of the task execution",
                        max_length=10,
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, help_text="When the task started", null=True
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, help_text="When the task finished", null=True
                    ),
                ),
                (
                    "result",
                    models.JSONField(
                        blank=True,
                        help_text='Task result (e.g., {"updated": 5})',
                        null=True,
                    ),
                ),
                (
                    "error",
                    models.TextField(
                        blank=True, help_text="Error message if failed", null=True
                    ),
                ),
                (
                    "duration",
                    models.DurationField(
                        blank=True, help_text="Execution time", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Task States",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["task_name", "state"],
                        name="vod_tasksta_task_na_149c00_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="vod_tasksta_created_c5c3ce_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255)),
                (
                    "original_package",
                    models.FileField(blank=True, upload_to="packages/"),
                ),
                (
                    "mezzanine_video",
                    models.FileField(blank=True, upload_to="mezzanine/"),
                ),
                (
                    "hevc_archive",
                    models.FileField(blank=True, upload_to="archive/hevc/"),
                ),
                ("dash_directory", models.CharField(blank=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("uploaded", "Uploaded"),
                            ("adi_validated", "ADI Validated"),
                            ("processing", "Processing"),
                            ("ready", "Ready"),
                            ("rejected", "Rejected"),
                            ("error", "Error"),
                        ],
                        default="uploaded",
                        max_length=20,
                    ),
                ),
                ("processing_log", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "get_latest_by": "modified",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Stream",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stream_protocol",
                    models.CharField(
                        choices=[("hls", "hls"), ("dash", "dash"), ("mss", "mss")],
                        max_length=4,
                    ),
                ),
                ("uri", models.URLField(max_length=512)),
                (
                    "edge",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="streams",
                        to="vod.edge",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("edge", "stream_protocol"), name="unq_edge_proto"
                    )
                ],
            },
        ),
    ]
