# Generated by Django 5.2.8 on 2025-12-02 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vod", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="edge",
            old_name="content_duration_ms",
            new_name="content_duration",
        ),
    ]
