# Generated by Django 5.2.8 on 2025-12-02 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vod", "0002_rename_content_duration_ms_edge_content_duration"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ActiveTaskRecord",
        ),
        migrations.DeleteModel(
            name="QueueStatus",
        ),
        migrations.DeleteModel(
            name="TaskState",
        ),
        migrations.DeleteModel(
            name="WorkerStatus",
        ),
    ]
