# Generated by Django 5.2.8 on 2025-12-02 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vod", "0003_delete_activetaskrecord_delete_queuestatus_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Offer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("offer_id", models.CharField(max_length=255, null=True)),
                ("expiration_date", models.DateTimeField(null=True)),
                (
                    "edge",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vod.edge",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="stream",
            name="offer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="offers",
                to="vod.offer",
            ),
        ),
    ]
