# Generated by Django 5.2.8 on 2025-12-02 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vod", "0004_offer_stream_offer"),
    ]

    operations = [
        migrations.AddField(
            model_name="offer",
            name="env",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
