# Generated by Django 5.2.8 on 2025-12-02 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vod", "0005_offer_env"),
    ]

    operations = [
        migrations.AlterField(
            model_name="offer",
            name="env",
            field=models.CharField(default="prod", max_length=255, null=True),
        ),
    ]
