# Generated by Django 5.2.8 on 2025-12-02 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vod", "0006_alter_offer_env"),
    ]

    operations = [
        migrations.AlterField(
            model_name="offer",
            name="env",
            field=models.CharField(
                choices=[("stag", "Stag"), ("prod", "Prod")],
                default="stag",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="stream",
            index=models.Index(fields=["uri"], name="vod_stream_uri_17144d_idx"),
        ),
    ]
