# Generated by Django 5.2.8 on 2025-12-02 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vod", "0007_alter_offer_env_stream_vod_stream_uri_17144d_idx"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="stream",
            constraint=models.UniqueConstraint(
                fields=("offer", "uri"), name="unq_offer_uri"
            ),
        ),
    ]
