# Generated by Django 5.2.8 on 2025-12-03 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vod", "0008_stream_unq_offer_uri"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="offer",
            index=models.Index(
                fields=["offer_id"], name="vod_offer_offer_i_7704d2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="offer",
            index=models.Index(fields=["env"], name="vod_offer_env_a0dc35_idx"),
        ),
        migrations.AddConstraint(
            model_name="offer",
            constraint=models.UniqueConstraint(
                fields=("offer_id", "env"), name="unq_offer_env"
            ),
        ),
    ]
