# Generated by Django 5.2.8 on 2025-12-03 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("insight", "0004_alter_task_state_alter_taskresult_state"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TaskResult",
        ),
    ]
