# Generated by Django 5.2.8 on 2025-12-03 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("insight", "0006_taskevent"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="type",
            new_name="name",
        ),
    ]
