# Generated by Django 5.2.8 on 2025-12-03 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("insight", "0007_rename_type_task_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="id",
            new_name="uuid",
        ),
    ]
