# Generated by Django 5.2.8 on 2025-12-03 16:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("insight", "0008_rename_id_task_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="last_updated",
            field=models.DateTimeField(
                blank=True, default=django.utils.timezone.now, null=True
            ),
        ),
    ]
