# Generated by Django 5.2.8 on 2025-12-03 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("insight", "0009_alter_task_last_updated"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="state",
            new_name="status",
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(fields=["worker"], name="insight_tas_worker_61f20f_idx"),
        ),
    ]
