# Generated by Django 5.2.8 on 2025-12-03 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("insight", "0012_alter_task_runtime"),
        ("vod", "0009_offer_vod_offer_offer_i_7704d2_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="provider",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tasks",
                to="vod.provider",
            ),
        ),
    ]
